stages:
  - build
  - test 
  - deploy 

build frontend:
  stage: build
  image: docker:29
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - | 
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then REGISTRY_TAG=latest;
      elif [[ $CI_COMMIT_REF_NAME == "development" ]]; then REGISTRY_TAG=development;
      else REGISTRY_TAG=$CI_COMMIT_REF_SLUG;
      fi
      docker buildx build -f frontend/Dockerfile -t $CI_REGISTRY_IMAGE/frontend:$REGISTRY_TAG \
      --cache-from=$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push .
      docker buildx build -f frontend/Dockerfile -t $CI_REGISTRY_IMAGE/frontend:test-$REGISTRY_TAG \
      --cache-from=test-$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push .
      echo "REGISTRY_TAG=$REGISTRY_TAG" >> build.env  
  artifacts:
    reports:
      dotenv: build.env 
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == "development"
    - if: $CI_COMMIT_REF_NAME =~ /feature/


build backend:
  stage: build 
  image: docker:29 
  before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - |
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then REGISTRY_TAG=latest;
      elif [[ $CI_COMMIT_REF_NAME == "development" ]]; then REGISTRY_TAG=development;
      else REGISTRY_TAG=$CI_COMMIT_REF_SLUG;
      fi
      docker buildx build -f backend/Dockerfile -t $CI_REGISTRY_IMAGE/backend:$REGISTRY_TAG \ 
      --cache-from=$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push .
      docker buildx build -f backend/Dockerfile -t $CI_REGISTRY_IMAGE/backend:test-$REGISTRY_TAG \
      --cache-from=test-$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push .
      echo "REGISTRY_TAG=$REGISTRY_TAG" >> build.env 
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == "development"
    - if: $CI_COMMIT_REF_NAME =~ /feature/

tests frontend:
  stage: test 
  image: $CI_REGISTRY_IMAGE/frontend:test-$REGISTRY_TAG 
  needs:
    - job: build frontend
      artifacts: true
  before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - echo "doing alot of cool tests"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == "development"

tests backend:
  stage: test 
  image: $CI_REGISTRY_IMAGE/backend:test-$REGISTRY_TAG 
  needs:
    - job: build backend 
      artifacts: true
  before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - echo "doing alot of cool tests"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == "development"

deploy development:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "development"
  script:
    - echo "Deploying to development enviorment..."

deploy production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "Deploying to production..."

