stages:
  - build
  - test
  - scan
  - deploy
  - cleanup

#Pipeline rule that can be reused
#This rule makes starts the job in main, development and every other branch with / in it
.always-rule: &always-rule
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
  - if: $CI_COMMIT_REF_NAME =~ /\//

.integration-rule: &integration-rule
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "true"

#Docker anchor template that can be reused for building frontend and backend
.docker-build: &docker-build
  stage: build
  image: docker:29
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

#Builds frontend in a docker container and pushes it to gitlab registry.
build frontend:
  <<: *docker-build
  rules: *always-rule
  variables:
    COMPONENT: frontend
  script:
    - |
      docker buildx create --use --name frontend-builder-$CI_JOB_ID --driver docker-container
      docker buildx build -f $COMPONENT/Dockerfile \
        -t $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_REF_SLUG \
        --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/$COMPONENT:cache-$CI_COMMIT_REF_SLUG \
        --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/$COMPONENT:cache-main \
        --cache-to=type=registry,ref=$CI_REGISTRY_IMAGE/$COMPONENT:cache-$CI_COMMIT_REF_SLUG,mode=max \
        --provenance=false --push $COMPONENT/
  after_script:
    - docker buildx rm frontend-builder-$CI_JOB_ID || true

#Builds backend in a docker container and pushes it to gitlab registry.
build backend:
  <<: *docker-build
  rules: *always-rule
  variables:
    COMPONENT: backend
  script:
    - |
      docker buildx create --use --name backend-builder-$CI_JOB_ID --driver docker-container
      docker buildx build -f $COMPONENT/Dockerfile \
        -t $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_REF_SLUG \
        --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/$COMPONENT:cache-$CI_COMMIT_REF_SLUG \
        --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/$COMPONENT:cache-main \
        --cache-to=type=registry,ref=$CI_REGISTRY_IMAGE/$COMPONENT:cache-$CI_COMMIT_REF_SLUG,mode=max \
        --provenance=false --push $COMPONENT/
  after_script:
    - docker buildx rm backend-builder-$CI_JOB_ID || true

build python:
  <<: *docker-build
  rules: *always-rule
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE/python-utils:latest --push --file scripts/python-Dockerfile .

#Deploys to development or feature branch
deploy development:
  stage: deploy
  image: $CI_REGISTRY_IMAGE/python-utils:latest
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.doe25.swarm.chas-lab.dev
    on_stop: stop_review
  script:
    - cd scripts
    - python3 deploy.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /\//

#Deploys to production, only runs when we push into main
deploy production:
  stage: deploy
  image: $CI_REGISTRY_IMAGE/python-utils:latest
  environment:
    name: production
    url: https://$CI_PROJECT_NAMESPACE_SLUG-$CI_PROJECT_NAME-production.doe25.swarm.chas-lab.dev
  script:
    - cd scripts
    - python3 deploy.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

.scan-image: &scan-image
  stage: scan
  image:
    name: aquasec/trivy:0.70.0
    entrypoint: [""]
  cache:
    paths:
      - .trivycache/
  variables:
    TRIVY_CACHE_DIR: .trivycache/
  before_script:
    - export TRIVY_USERNAME="$CI_REGISTRY_USER"
    - export TRIVY_PASSWORD="$CI_REGISTRY_PASSWORD"
  script:
    - trivy image
      --severity HIGH,CRITICAL
      --ignore-unfixed
      --exit-code 0
      --no-progress
      --format template
      --template "@/contrib/html.tpl"
      --output trivy-report-$COMPONENT.html
      $IMAGE
  artifacts:
    paths:
      - trivy-report-$COMPONENT.html
    expire_in: 1 week
    when: always

scan python:
  <<: *scan-image
  rules: *integration-rule
  needs:
    - job: build python
  variables:
    COMPONENT: python
    IMAGE: $CI_REGISTRY_IMAGE/python-utils:latest

scan frontend:
  <<: *scan-image
  rules: *integration-rule
  needs:
    - job: build frontend
  variables:
    COMPONENT: frontend
    IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG

scan backend:
  <<: *scan-image
  rules: *integration-rule
  needs:
    - job: build backend
  variables:
    COMPONENT: backend
    IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG

#Removes the environment manually when MR is done
stop_review:
  stage: cleanup
  image: $CI_REGISTRY_IMAGE/python-utils:latest
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - cd scripts
    - python3 delete-stack.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
      when: manual
    - if: $CI_COMMIT_REF_NAME =~ /\//
      when: manual
