stages:
  - build
  - test 
  - deploy 

# Builds frontend in a docker container and pushes it to gitlab registry.
# Saves the name of the REGISTRY_TAG in build.env file
# This stage will always run
build frontend:
  stage: build
  image: docker:29
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - | 
      docker buildx create --use --name mybuilder --driver docker-container
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then REGISTRY_TAG=latest;
      elif [[ $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH ]]; then REGISTRY_TAG=$DEVELOPMENT_BRANCH;
      else REGISTRY_TAG=$CI_COMMIT_REF_SLUG;
      fi
      docker buildx build -f frontend/Dockerfile \
      -t $CI_REGISTRY_IMAGE/frontend:$REGISTRY_TAG \
      -t $CI_REGISTRY_IMAGE/frontend:test-$REGISTRY_TAG \
      --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/frontend:cache-$REGISTRY_TAG \
      --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/frontend:cache-latest \
      --cache-to=type=registry,ref=$CI_REGISTRY_IMAGE/frontend:cache-$REGISTRY_TAG,mode=max \
      --provenance=false --push frontend/
      echo "REGISTRY_TAG=$REGISTRY_TAG" >> build.env
  artifacts:
    reports:
      dotenv: build.env 
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /\//

# Builds backend in a docker container and pushes it to gitlab registry.
# Saves the name of the REGISTRY_TAG in build.env file
# This stage will always run
build backend:
  stage: build 
  image: docker:29 
  before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - |
      docker buildx create --use --name mybuilder --driver docker-container
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then REGISTRY_TAG=latest;
      elif [[ $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH ]]; then REGISTRY_TAG=$DEVELOPMENT_BRANCH;
      else REGISTRY_TAG=$CI_COMMIT_REF_SLUG;
      fi
      docker buildx build -f backend/Dockerfile \
      -t $CI_REGISTRY_IMAGE/backend:$REGISTRY_TAG \
      -t $CI_REGISTRY_IMAGE/backend:test-$REGISTRY_TAG \
      --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/backend:cache-$REGISTRY_TAG \
      --cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/backend:cache-latest \
      --cache-to=type=registry,ref=$CI_REGISTRY_IMAGE/backend:cache-$REGISTRY_TAG,mode=max \
      --provenance=false --push backend/
      echo "REGISTRY_TAG=$REGISTRY_TAG" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /\//

build python:
  stage: build
  image: docker:29
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker buildx build -t ${CI_REGISTRY_IMAGE}/python-utils:latest --push --file scripts/python-Dockerfile .
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /\// 
      changes:
        - scripts/python-Dockerfile
        - scripts/deploy.py 
        - scripts/requirements.txt

# Verifys that all the images works correctly by trying to pull all images from the registry
verify images:
  stage: test
  image: docker:29
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  needs:
    - job: build frontend
      artifacts: true 
    - job: build backend
      artifacts: true 
    - job: build python
  script:
    - docker pull $CI_REGISTRY_IMAGE/frontend:$REGISTRY_TAG
    - docker pull $CI_REGISTRY_IMAGE/frontend:test-$REGISTRY_TAG
    - docker pull $CI_REGISTRY_IMAGE/backend:$REGISTRY_TAG
    - docker pull $CI_REGISTRY_IMAGE/backend:test-$REGISTRY_TAG
    - docker pull $CI_REGISTRY_IMAGE/python-utils:latest
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /\//
      changes:
        - frontend/Dockerfile
        - backend/Dockerfile
        - scripts/python-Dockerfile

# This dosnt do anything yet. But will add developers unit tests here.
tests frontend:
  stage: test 
  image: $CI_REGISTRY_IMAGE/frontend:test-$REGISTRY_TAG 
  needs:
    - job: build frontend
      artifacts: true
  before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - echo "doing alot of cool tests"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH 

# This dosnt do anything yet. But will add developers unit tests here.
tests backend:
  stage: test 
  image: $CI_REGISTRY_IMAGE/backend:test-$REGISTRY_TAG 
  needs:
    - job: build backend 
      artifacts: true
  before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - echo "doing alot of cool tests"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH

#Deploys to development or feature branch
deploy development:
  stage: deploy
  image: ${CI_REGISTRY_IMAGE}/python-utils:latest
  environment: 
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAMESPACE_SLUG-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.doe25.swarm.chas-lab.dev
#    on_stop: stop_review
  script:
    - cd scripts
    - python3 deploy.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $DEVELOPMENT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /\//

#Deploys to production, only runs when we push into main
deploy production:
  stage: deploy
  image: ${CI_REGISTRY_IMAGE}/python-utils:latest
  environment:
    name: production/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAMESPACE_SLUG-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.doe25.swarm.chas-lab.dev
  script:
    - cd scripts
    - python3 deploy.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

