services:
  frontend:
    image: ${CI_REGISTRY_IMAGE/frontend}:${image_tag}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"

        - "traefik.http.routers.${STACK_NAME}-http.rule=Host(`${STACK_NAME}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_NAME}-http.middlewares=https-redirect"

        - "traefik.http.routers.${STACK_NAME}-https.rule=Host(`${STACK_NAME}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-https.tls=true"
        - "traefik.http.routers.${STACK_NAME}-https.tls.certresolver=le"

        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=5173"

  backend:
    image: ${CI_REGISTRY_IMAGE/backend}:${image_tag}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"

        - "traefik.http.routers.${STACK_NAME}-http.rule=Host(`${STACK_NAME}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_NAME}-http.middlewares=https-redirect"

        - "traefik.http.routers.${STACK_NAME}-https.rule=Host(`${STACK_NAME}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-https.tls=true"
        - "traefik.http.routers.${STACK_NAME}-https.tls.certresolver=le"

        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=3000"


networks:
  traefik-public:
    external: true

