services:
  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        - VITE_API_URL=http://localhost:3000
        - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    image: local/frontend:latest
    ports:
      - "8080:8080"
    networks:
      - internal
      - traefik-public
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: prod
    image: local/backend:latest
    ports:
      - "3000:3000"
    networks:
      - internal
    env_file:
      - .env

  pgadmin:
    ports:
      - "5050:80"
    networks:
      - internal

  drizzle:
    build:
      context: ./backend
      target: dev
    container_name: drizzle
    command: ["sh", "-c", "npm run db:studio -- --host 0.0.0.0"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "4983:4983"
    networks:
      - internal
    depends_on:
      - db

networks:
  traefik-public:
    driver: bridge
    external: false
  internal:
    driver: bridge