services:
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      target: dev
    restart: unless-stopped
    container_name: backend
    command: ["sh", "-c", "npm run db:migrate && npm run dev"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - S3_URL=${S3_URL}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - access_key_S3=${access_key_S3}
      - secret_key_S3=${secret_key_S3}
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: imresamu/postgis:18-3.6-alpine
    restart: unless-stopped
    container_name: postgis-database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  drizzle:
    build:
      context: ./backend
      target: dev
    container_name: drizzle
    command: ["sh", "-c", "npm run db:studio -- --host 0.0.0.0"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - 4983:4983
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
