services:
  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:${image_tag}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"
        - "traefik.http.routers.${stack_name}-http.rule=Host(`${stack_name}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${stack_name}-http.entrypoints=http"
        - "traefik.http.routers.${stack_name}-http.middlewares=https-redirect"
        - "traefik.http.routers.${stack_name}-https.rule=Host(`${stack_name}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${stack_name}-https.entrypoints=https"
        - "traefik.http.routers.${stack_name}-https.tls=true"
        - "traefik.http.routers.${stack_name}-https.tls.certresolver=le"
        - "traefik.http.services.${stack_name}.loadbalancer.server.port=8080"

  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${image_tag}
    networks:
      - traefik-public
      - internal
    command: ["sh", "-c", "sleep 5 && npm run db:migrate && npm run start"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"
        - "traefik.http.routers.${stack_name}-backend-http.rule=Host(`api.${stack_name}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${stack_name}-backend-http.entrypoints=http"
        - "traefik.http.routers.${stack_name}-backend-http.middlewares=https-redirect"
        - "traefik.http.routers.${stack_name}-backend-https.rule=Host(`api.${stack_name}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${stack_name}-backend-https.entrypoints=https"
        - "traefik.http.routers.${stack_name}-backend-https.tls=true"
        - "traefik.http.routers.${stack_name}-backend-https.tls.certresolver=le"
        - "traefik.http.services.${stack_name}-backend.loadbalancer.server.port=3000"
    depends_on:
      - db

  db:
    image: postgis/postgis:18-3.6-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - traefik-public
      - internal
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PWD}
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"
        - "traefik.http.routers.${stack_name}-pgadmin-http.rule=Host(`db.${stack_name}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${stack_name}-pgadmin-http.entrypoints=http"
        - "traefik.http.routers.${stack_name}-pgadmin-http.middlewares=https-redirect"
        - "traefik.http.routers.${stack_name}-pgadmin-https.rule=Host(`db.${stack_name}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${stack_name}-pgadmin-https.entrypoints=https"
        - "traefik.http.routers.${stack_name}-pgadmin-https.tls=true"
        - "traefik.http.routers.${stack_name}-pgadmin-https.tls.certresolver=le"
        - "traefik.http.services.${stack_name}-pgadmin.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true
  internal:
    driver: overlay
