apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: litter-hero_db
  DB_PORT: "5432"
  S3_URL: https://group-2-chas-challenge-2026.hel1.your-objectstorage.com
  S3_BUCKET: group-2-chas-challenge-2026
  S3_REGION: garage
