---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry
  namespace: doe25-group-2
spec:
  encryptedData:
    .dockerconfigjson: AgDtt/8qFZLcKJ+iNs8DhU24IWq9MH7AiKIOOOZCX9U49TV+VbliKHxuvsZf3BlmZhMNYODkPeD7ldxTutqwf/l6Wxdnu+ZrjB9QuT57T02jqzKHeZFptxI1DpjbPtFNIILJ6It3Jp71zr9SPyqY7tCrDw48zSvMrA6kO3P+zUPgPJLqb9guCNe/QypcHuTRsNXZgb/eMw+njFXY2jm7QmY63V9OEEwNhYTU7S3WJkg5TbikbU9XdhSVxp1NDfwtMV1fsFY+Fo6B5hesTUjxkQiz2YPb38nPl8xVhAsz5w31vtcdeywKQWxJ8PCEq+Ja3263Bx4F0/ouy4JZAwI4SJ1HXCna/3YZBJXYTOLjjC9/sV15gDnLU5nCagazSvcwQrPo7r2jW7+QnKPu+2fcTG04D9gdVvc/Xzph5Vli0r27KNilr5ASv4rNq1s/KiiCF4Xwmv6VlUn3gvJsXM9XXuyA1uPI4eDhNSOuJgV+6uNfZLlbq6PEehFLq8ObuMlnrv5uDl41Z2qcx+PEm+RjucOLX9qAz7BSXV+PGjNibMaZadF82Uftehc1zoJsYheD3Eh7zg2Xf/x8S5bCmS8u/lEmIbB5MKx2q4dQ0QBLQG7BoOBaQIPx1lkpEa2TFXkpXP8iODjaKvxwBCJKgAEJZ49/rcfyLprhFe4SQWOEaVeESceitGt4Nbbf/q6SqQAqd9/HPDKdPi3P3WndwOCuNVbEJRmkASnHyQAzClMuwbyEvQZBVYBgvnG+zoDlmYZotiMBdUH/VJ5HPBMqIL1T6kU5Blm5cz//0cIyxEzVbx0NfAXPVnh11o4iZHRYy5nG1Kh8Jx3SwdzgyG0MwS9wL8KjYfR6NRK6s4XhGqFA4F8zzuEgdd/N+UHDHXeOgb9b22rjEIpwzHFJya2XOaE=
  template:
    metadata:
      name: gitlab-registry
      namespace: doe25-group-2
    type: kubernetes.io/dockerconfigjson
