apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry
  namespace: doe25-group-2
spec:
  encryptedData:
    .dockerconfigjson: AgDonH6BreLVdOjXKTgK0lZOZfMpTgsfj+LDeK7gGw+Jr1B8s0WibCreze1jQOhlkNpKC0lmGmNpqzB10lFAmOoxMqmod/AAn09WMIMvbT6283o3clI/Q70VEmfmGKkwoXjvzXnpdPzTJq/OqSdNqXT9FxzZvhePppwMfEoidBmMIvlgLeTUX4ShpopzDQdiWsN2QB0dyRajpKhdHPdSn2/lMkhOWdTCbuIgcLWNxCArzABwHmpV3RRMKc3+I18e9nSTMMgAxjYjWIV6HASzKTPt0RRKCL0riprTXe6PFjQ6X3J1irqSpdpe1Itewu1sTynFXxD97DIspGaci+vHjS9v6IRwTssdovsro4bJVnjcS0565//5swjNCs0u6JKVtodnIKsrjemkPj18tIjmTLNUonibMsaAX5Ly0+nDRxHgk36J6dfjM0gaVdine2BsysESrrvRGQVhNSlJFHLY84vkoKupCUgmzlLp8PCa26Gs3o3ZTyJVOrrOIXEPfzQj9KxUuXcPpgwB0ayTSXBXlhDgds6Txh3vRDjnwYTPtaM89EY1TOvKfarcIpTKQL/Bv173AlHJ7B45ZoFVgBdGGvmPUL7iKnlAjSpf8x+Tv0Ru0ET25zyZ7dueYb93edbmnXOoqqvIXeeVI0qBohQFPB2MU5KR9QUjmYLqsghXoN59XwV63MWieeENAJ7mpJ+5uJ37/s8xcqmd8UmuigboCqNM6BIESJu9MvGD5fAPFsoJpO3ovPyS2PdXvGnFXz8wY1DdbbgomLSN+iXDGQTkNRYMk4hMR7fCGmK3Rl6jTkRqYWrz8CuQSY+tPOKNrB2NZk2a1yGK5g6mAUGjmgLwKfgUGcZmrA3ms/wj46I82Lc5YK4ieP1xHo766oh+6EF1j6JRydDKFAduga2/
  template:
    metadata:
      name: gitlab-registry
      namespace: doe25-group-2
    type: kubernetes.io/dockerconfigjson
