---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: test-basic-auth
  namespace: doe25-group-2
spec:
  encryptedData:
    users: AgBxGBESgGbLncQ6OFqWrMw07rM3EK35Yr7iyet8fevah9QPU0HtPtJ4Ni6MNrqD3kQmRp8USu+2I2TbfzDjOx2u3OBB7nWFgp7VOCd+3OO+Exrbk3vXdKPZ9remh1UrXLCA413dxVDkyJCmlhKEPjO/uFWZQKjNnFxyrniyouuAheTenpui0RFw3rLTdJkaXNRflv6WgdF2A0Qh/xgvtYdQaktaFEaBTvwDV4R5OmDJdr07BQ+o5aTzkUsxn/UxgqZxWigYvHl3q5wFgDLYDDhrZmOYFLUfdw488JWfzYpR1+zFMVaNX2vrZXJ4l2tc/tnnH9Rj1kxhlor4Y6Rxq9Ee9i3hKyxTrZkINLKF83N2tDwU+n/fc4uKI6sVQe+3ibSiiolfVr1ZOelgRX2fTzjxjVDUlZbiiOgiu2YuscxBHuD9T1xwapswzPc6xHKw4O7308QLdMxICIRksh8x6PHzoEQAsrtdSylyB9AFeuKTBiW0hgNuMeyWPudxBKmikr+8rluyWTN3JQLxw7DvPQuqdmfrrwo3L/JoxotA3AoJgRkQ6yHdN1MJB2pf5ppSzf+jaJi7WQG+QHI6o7lLnDmh21O58D+MGF8ZBTZ7M+5UvylVqFYJ8mJwKnCf8e+kDlCVKX4YTS29ZUA3EULKt9o5ujSo53ZP6RMm+t/J5ibaI9htMi3Nx4C/eVXBqbIN426ZRJpBArf1yQWI0XRGfRwha+FYtFpp0s3Jmlhi+WtcPvgdM01vNH9HhvHRSG0Xer9VUtg8/bfLAiJFAdXO+GBLgqF4zK8=
  template:
    metadata:
      name: test-basic-auth
      namespace: doe25-group-2
