apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cc-basic-auth
  namespace: doe25-alexander-piensoho
spec:
  encryptedData:
    users: AgApNZO4Qt4/ekL3FGkzSBtAOPh+dbNm75byaKEtcT2o4Z35rwiFzNRxiJZ50qfaEMjUJiaJBpKsNPItg3olZtn5CDIZ7eGE2I+IH4ycHI2U/pK1FXlWHTJIAkQBS654AQpSGUMzRkYJcaWA6Db8Bt3RuDjv+GTseQdW3napHstGAXoaM1NkH6JDmAdRh7cWSGgx6k6AR9J4IzXMyFygvK280CrCwpYbqvcoT50RBa1GohKuH3VS8jxQJmFxFPi6+J7al+T43gxYh7E6puwvYge8JZkcqLEEk6B3XVo6W9MjBidha7d2oKh+thHJkgSP7gePYJvVK9Zr9AHEVwkBz0N3LKNE52e/aHtm8tq9chgigHNz9MUQ58Ivn2KfD5l2X5xfzZnFdH77OJpsz/U2+/d2A9NCVdQoQyygmCXD4VkC+v7yZA+3yAPVEbOtAle4MAWOTlYXfatdwsBTraR8Y0a7ZBS+CxeMfEND6+gAAT0bcMZeuV9L/qV42LauCQYNJtqnFV+1NMbcoL2geMki//+SgI++SlPYbGwkjX2mw5FESxVJSV5khvxbkx3ywMlFoErk/SK5IUwqmPWS5gHRrOuMRNGSOK33tawrAAsuE/KIbvZKiByfjQI9f5xEPAGAcgtsP3tffYKNYW/Kw/5kqNeFCeyV6Us85piQbLFtP44OLW+f0PUklvuuI8QVqXNgCEUN3JTXdjeg4SEey88US79g2L2KbxZbi2/US18XfD91HngnuAD4Ba0QXlFw2xdiE7Y21V41IzdCRL6PSzSUBXxe1PFP
  template:
    metadata:
      name: cc-basic-auth
      namespace: doe25-alexander-piensoho
