---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-secret
  namespace: doe25-group-2
spec:
  encryptedData:
    RESEND_API_KEY: AgBaQq86iFZ4GB98grgHSOpssmKHDPfvf+H8wdlxDlNBYHLKka69WGaD812XSfNZ9Al68flt7sTcEoBbILFwOw9R+IsSv29dWbt05UKn5IF4u3PiCS2v+cVHoxllNfsSXK5bBZ81QSp86Xfn7vuqlCpHoFDd4Mukl/TeqFya+aolh9NzGgm+i54zc7x8ro/vhb6kmxezyJj10nqJVlmq3BYDNnq/JoGLxF1xJn0vrtNEVIFeWsLZFdGSWEsCDApWdGEVspa+yiS3PBmVcgvGRIc86a+EdWD78dCVkiIxAqN4vnSHpiAqNCK08Kv0cXpaYcyoFHM9NnADABwAhyVPzJWn65cyy5l3OtPg3kdSfjPCfsKwP37kKjapQOQGZcUyr1UuhAum90diJ3GDluOSfHk3J6FX8ppoHKvDJga5QxOctomes7HnqKfQU5hEU61kj6vvHv0AA+VapaUTVMzmlLHlF2sNp01qE6mIkVZigdEbR2OKgkkkM+xcYew4iVFremPqSfj4pNb0qzxiQMnAf7hB+LocprTeI8DGRxc+xdfPYwBeufmEUgEpYGa0OFnFwfohfyHeWa607Ibnye1u3+w/1A4cyJ4wo6lU6+t+tzYDK0lrmTm410CytEo1v1HF27ZPivksjSCudG4WrH8W+4QPir/7cZFDoxapKxGOft+YPuCJLaABuLEJMoStv+4DyjCgMnl5BQa64jf8YM61DmMuJWsUccfNbN2A8jxz/S2ioFqgINw=
  template:
    metadata:
      name: resend-secret
      namespace: doe25-group-2
